apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
        - name: app
          image: us.gcr.io/staging-178214/master:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: "REDIS_URL"
              value: "redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT)"