apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
        - name: app
          image: bezelga/ink:v.2
          imagePullPolicy: Always
          env:
            - name: "REDIS_URL"
              value: "redis://$(REDIS_SERVICE_HOST):$(REDIS_SERVICE_PORT)"
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    name: app
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    name: app