apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: path-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: Path
spec:
  rules:
  - host: ink.fabiano.io
    http:
      paths:
      - path: /app
        backend:
          serviceName: app
          servicePort: 80